### ISSUE TITLE
I want to be added!

### ISSUE THREAD

**Issue by nickgvm20** [edoardottt/spark-ar-creators#16]
Username: <nickjeffz>
Link to Profile: https://www.instagram.com/<nickjeffz>

- [ ] I added a star on this project
- [ ] I checked (with CTRL+F) if I'm yet on this list

**Comment by edoardottt** [comment]
You have to complete all the form before being added :P

**Comment by debbiemenezes** [comment]
Debbie Menezes
Instagram.com/debbiemenezes

**Comment by edoardottt** [comment]
Thanks! I've scheduled your ig account. I'll add you soon.

Drop a star to support the project :)

Have a nice day, 

  edoardottt https://www.edoardoottavianelli.it
