### ISSUE TITLE
I want to be added!

### ISSUE THREAD

**Issue by jatin-pahuja** [edoardottt/spark-ar-creators#20]
- Username: farziphotographer
  
- Link to Profile: https://www.instagram.com/farziphotographer   
- [x] I opened an issue
- [x] I added a star on this project
- [x] I checked (with CTRL+F) if I'm yet on this list

**Comment by edoardottt** [comment]
Done! 

Have a nice day, edoardottt

Edoardo Ottavianelli, https://edoardoottavianelli.it
