### ISSUE TITLE
I want to be added!

### ISSUE THREAD

**Issue by Frenzyritz13** [edoardottt/spark-ar-creators#21]
- Username: frenzy.works
  
- Link to Profile: https://www.instagram.com/frenzy.works

- [x] I opened an issue
- [x] I added a star on this project
- [X] I checked (with CTRL+F) if I'm yet on this list

**Comment by edoardottt** [comment]
Done! 

Have a nice day, edoardottt

Edoardo Ottavianelli, https://edoardoottavianelli.it
