### ISSUE TITLE
I want to be added!

### ISSUE THREAD

**Issue by pranjalnahata** [edoardottt/spark-ar-creators#22]
- Username: pranjalnahata
  
- Link to Profile: https://www.instagram.com/pranjalnahata

- [x] I opened an issue
- [x] I added a star on this project
- [x] I checked (with CTRL+F) if I'm already in this list

**Comment by edoardottt** [comment]
Added!

Have a nice day! :+1: 

edoardottt, https://www.edoardoottavianelli.it
