### ISSUE TITLE
I want to be added!

### ISSUE THREAD

**Issue by naupaw** [edoardottt/spark-ar-creators#24]
- Username: _.nfikri
  
- Link to Profile: https://www.instagram.com/_.nfikri

- [x] I opened an issue
- [x] I added a star on this project
- [x] I checked (with CTRL+F) if I'm already in this list

**Comment by edoardottt** [comment]
Done! 

Have a nice day, edoardottt

Edoardo Ottavianelli, https://edoardoottavianelli.it
