### ISSUE TITLE
I want to be added!

### ISSUE THREAD

**Issue by elvinmendoza** [edoardottt/spark-ar-creators#25]
- Username: elvinmendoza
  
- Link to Profile: https://www.instagram.com/elvinmendoza

- [x] I opened an issue
- [x] I added a star on this project
- [ ] I checked (with CTRL+F) if I'm already in this list

**Comment by edoardottt** [comment]
Ok. I've scheduled your profile name. I'll add you soon.

:100: Star the project to support it :100: 

Have a nice day, edoardottt

  Edoardo Ottavianelli, https://www.edoardoottavianelli.it
