### ISSUE TITLE
I want to be added!

### ISSUE THREAD

**Issue by ofekgrego** [edoardottt/spark-ar-creators#26]
- Username: INSERT-USERNAME-HERE
  filtereal

- Link to Profile: https://www.instagram.com/INSERT-USERNAME-HERE
https://www.instagram.com/filtereal/

- [x] I opened an issue
- [ ] I added a star on this project
- [ ] I checked (with CTRL+F) if I'm already in this list

**Comment by edoardottt** [comment]
Ok. I've scheduled your profile name. I'll add you soon.

Have a nice day, edoardottt

  Edoardo Ottavianelli, https://www.edoardoottavianelli.it
