### ISSUE TITLE
I want to be added!

### ISSUE THREAD

**Issue by greevak** [edoardottt/spark-ar-creators#28]
- Username: gr33v
  
- Link to Profile: https://www.instagram.com/gr33v

- [x] I opened an issue
- [x] I added a star on this project
- [x] I checked (with CTRL+F) if I'm already in this list

**Comment by edoardottt** [comment]
Ok. I've scheduled your profile name. I'll add you soon.

Have a nice day, edoardottt

  Edoardo Ottavianelli, https://www.edoardoottavianelli.it
