### ISSUE TITLE
I want to be added❤️

### ISSUE THREAD

**Issue by rbs250** [edoardottt/spark-ar-creators#30]
- Username: thebensimon
  
- Link to Profile: https://www.instagram.com/thebensimon

- [x] I opened an issue
- [x] I added a star on this project
- [x] I checked (with CTRL+F) if I'm already in this list

**Comment by edoardottt** [comment]
Ok. I've scheduled your profile name. I'll add you soon.

Have a nice day, edoardottt

  Edoardo Ottavianelli, https://www.edoardoottavianelli.it
