### ISSUE TITLE
I want to be added ❤️

### ISSUE THREAD

**Issue by pawonair** [edoardottt/spark-ar-creators#31]
- Username: pawonarts
  
- Link to Profile: https://www.instagram.com/pawonarts/

- [x] I opened an issue
- [x] I added a star on this project
- [x] I checked (with CTRL+F) if I'm already in this list

**Comment by edoardottt** [comment]
Added!

Have a nice day, edoardottt

  Edoardo Ottavianelli, https://www.edoardoottavianelli.it
