### ISSUE TITLE
I want to be added❤️

### ISSUE THREAD

**Issue by harshpalan** [edoardottt/spark-ar-creators#32]
- Username: harsh.palan
  
- Link to Profile: https://www.instagram.com/harsh.palan/

- [x] I opened an issue
- [x ] I added a star on this project
- [ ] I checked (with CTRL+F) if I'm already in this list

**Comment by edoardottt** [comment]
Added! :+1: 

Have a nice day, edoardottt

  Edoardo Ottavianelli, https://www.edoardoottavianelli.it
