### ISSUE TITLE
I want to be added❤️

### ISSUE THREAD

**Issue by heynaavi** [edoardottt/spark-ar-creators#33]
- Username: naaaviiii
  
- Link to Profile: https://www.instagram.com/naaaviiii/

- [x] I opened an issue
- [x] I added a star on this project
- [x] I checked (with CTRL+F) if I'm already in this list

**Comment by edoardottt** [comment]
Added! :+1: 

Have a nice day, edoardottt

  Edoardo Ottavianelli, https://www.edoardoottavianelli.it
