### ISSUE TITLE
I want to be added❤️

### ISSUE THREAD

**Issue by mezza2000** [edoardottt/spark-ar-creators#34]
- Username: Matteo.mezzanato
  
- Link to Profile: https://instagram.com/matteo.mezzanato?igshid=qr8t5xhnnxg0

- [x] I opened an issue
- [ ] I added a star on this project
- [ ] I checked (with CTRL+F) if I'm already in this list

**Comment by edoardottt** [comment]
Added! :+1: 

Have a nice day, edoardottt

  Edoardo Ottavianelli, https://www.edoardoottavianelli.it
