### ISSUE TITLE
I want to be added❤️

### ISSUE THREAD

**Issue by keiranlovett** [edoardottt/spark-ar-creators#35]
- Username: ShadowFactory
  
- Link to Profile: https://www.instagram.com/shadowfactory.io

- [x] I opened an issue
- [x] I added a star on this project
- [x] I checked (with CTRL+F) if I'm already in this list

**Comment by edoardottt** [comment]
Added! :+1: 
If you want to support the project, drop a star :1st_place_medal: 

Have a nice day, edoardottt

Edoardo Ottavianelli, https://www.edoardoottavianelli.it
