### ISSUE TITLE
I want to be added❤️

### ISSUE THREAD

**Issue by lopeselio** [edoardottt/spark-ar-creators#36]
- Username: lopeselio
  
- Link to Profile: https://www.instagram.com/heliosz.17/

- Link to my effects
https://www.instagram.com/ar/263807801375356
https://www.instagram.com/ar/178149550302847
https://www.instagram.com/ar/2646332608973624

- [x] I opened my first issue
- [x] I added a star on this project
- [x] I checked (with CTRL+F) if I'm already in this list

Would be grateful if you would add me to the list.

**Comment by edoardottt** [comment]
Added! :+1: 
If you want to support the project, drop a star :1st_place_medal: 

Have a nice day, edoardottt

Edoardo Ottavianelli, https://www.edoardoottavianelli.it
