### ISSUE TITLE
I want to be added❤️

### ISSUE THREAD

**Issue by soubhagya1999** [edoardottt/spark-ar-creators#41]
- Username: @so_u_bhagya.1999
  
- Link to Profile: https://www.instagram.com/so_u_bhagya.1999/

- [x] I opened an issue
- [x] I added a star on this project
- [x] I checked (with CTRL+F) if I'm already in this list

**Comment by edoardottt** [comment]
Added !

Have a nice day, edoardottt

https://www.edoardoottavianelli.it/
