### ISSUE TITLE
I want to be added❤️

### ISSUE THREAD

**Issue by gereltuya** [edoardottt/spark-ar-creators#43]
- Username: greendot.vip
  
- Link to Profile: https://www.instagram.com/greendot.vip

- [x] I opened an issue
- [x] I added a star on this project
- [x] I checked (with CTRL+F) if I'm already in this list

**Comment by edoardottt** [comment]
Added! :+1:

Have a nice day, edoardottt

Edoardo Ottavianelli, https://www.edoardoottavianelli.it
